Part_03 DB, ORM. Rails generators and migrations.
zdvbind/TestGuru pull request #2
Opened 2021-04-21 09:55 UTC by zdvbind

2021-04-21 19:23 UTC, BubuntuClu requested changes

2021-04-21 19:23 UTC, BubuntuClu commented on db/migrate/20210421070956_create_tests.rb
> +      t.integer :level
нужно еще добавить связь с таблицей категорий - внешний ключ, индекс

2021-04-21 19:23 UTC, BubuntuClu commented on db/migrate/20210421072934_create_answers.rb
> +
нужно еще добавить связь с таблицей вопросов - внешний ключ, индекс

2021-04-21 19:23 UTC, BubuntuClu commented on db/migrate/20210421072911_create_questions.rb
> +      t.text :body
нужно еще добавить связь с таблицей тестов - внешний ключ, индекс

2021-04-23 06:39 UTC, BubuntuClu commented on db/migrate/20210422064651_add_references.rb
> +    add_reference :tests, :categories, foreign_key: true
лучше было откатить миграцию создания таблицы и туда добавить создание внешний ключей. сейчас у тебя в одной миграции намешаны изменения в трех таблицах, так плохо делать, потому что при откате этой миграции ты заденешь все 3 таблицы

у тебя во множественном числе используется вторая таблица, а должно быть в единственном.

`t.integer "questions_id"` видишь какое поле получилось? это неправильно

2021-04-23 12:18 UTC, BubuntuClu commented on db/migrate/20210421070956_create_tests.rb
> +    add_reference :tests, :category, foreign_key: true
будет совсем круто, если ты это поместишь внутрь блока создания таблицы.

синтаксис будет `t.references ...`

2021-04-23 13:06 UTC, zdvbind commented on db/migrate/20210421070956_create_tests.rb
> +    add_reference :tests, :category, foreign_key: true
О, спасибо, не знал как это сделать прямо внутри блока создания таблицы. В итоге нашел документацию ActiveRecord::ConnectionAdapters::Table < Object

2021-04-23 13:12 UTC, merged